### ISSUE TITLE
Tests fail due to a `DimensionMismatch` when using the distributed branch.

### ISSUE THREAD

**Issue by jakebolewski** [andreasnoack/TSVD.jl#1]

**Comment by andreasnoack** [comment]
Code example!

**Comment by andreasnoack** [comment]
Oh I see. The tests. I'll take a look

**Comment by andreasnoack** [comment]
Yes. On the `anj/dist` branch this is broken right now because I've disabled the conversion from `Vector{Vector{T}}` to `Matrix{T}` because it would be crazy inefficient for `DArray`s. I'll have to find away to generically convert the to a matrix when we are done with the iterations.

We could also consider to convert to a `Matrix` earlier, but then the problem would be that we cannot easily append columns to `Matrix`.
